# Generated by Django 2.1.7 on 2019-03-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='create_date',
            new_name='created_at',
        ),
    ]
