# Generated by Django 2.1.7 on 2019-03-24 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190318_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
